### ISSUE TITLE
copy to clipboard icon positioning breaks on scroll

### ISSUE THREAD

**Issue by Deep-Codes** [100mslive/100ms-docs#241]
Steps to reproduce:

Visit: https://docs.100ms.live/server-side/v2/features/room

Scroll horizontally the code snippet 

![e09ccf14-076e-4db8-b7b9-3744924710e6](https://user-images.githubusercontent.com/61158210/135699967-55afb34e-577e-48ff-9481-e30a9a24038a.png)

**Comment by Meowyam** [comment]
I can check out this issue.

**Comment by Deep-Codes** [comment]
> I can check out this issue.

Awesome let me know if help needed.

**Comment by tusharnankani** [comment]
Hey

I was just going through 100-ms docs. Thought I'll take a look at the issues, and this one _seemed_ like a quick fix. 

But good god! Turned out I was scratching my head at it for hours now. Either this is an actual problem OR it is very trivial and I am messing up big time _:embarassed:_
I have tried so many combinations now, but also learned SO much haha.

I think, I am the closest now, so here it goes: 

## Potential Fix

So here's the problem: 

https://github.com/100mslive/100ms-docs/blob/e3a1fdd2b85004260957463364c867b7fb725973/components/Code.tsx#L97-L99

So, after [realizing](https://css-tricks.com/creating-sliding-effects-using-sticky-positioning) the difference b/w sticky and fixed. We need `position: sticky` or `fixed`, `fixed` would work in this case. But `top`, `right` won't work and will be relative to the whole body apparently.

So using `margin` now.

```css
.copied {
  position: fixed;
  margin: 10px 0 0 clamp(150px, 690px, 80vw);
}
```

### Behaviour 


https://user-images.githubusercontent.com/61280281/150996729-8828084c-6a3c-4b80-bfff-9b64c189a9d9.mp4


Hope this helps!

Also, don't worry about that constantly hovered icon, I have set `hovered` to `true` for testing :P

![image](https://user-images.githubusercontent.com/61280281/150996968-f814c78a-7b9e-4d1a-b54e-369f9a97a226.png)

### Extras

Side note: we also have some redundant CSS, for the same `.copied` and `button`, not sure why.

https://github.com/100mslive/100ms-docs/blob/e3a1fdd2b85004260957463364c867b7fb725973/components/Code.tsx#L76-L80

---

Alternate Solutions: 

- Wrapping the command. 
  - Better alignment.
  - Better readability.
  - Better UX.

[Example](https://www.cloudskillsboost.google/focuses/560?parent=catalog#:~:text=the%20Windows%20Server-,Test%20the%20status%20of%20Windows%20Startup,-After%20a%20short)

So, something like this: 
![image](https://user-images.githubusercontent.com/61280281/150994580-074bc56f-d990-4ac2-b533-40bee95326ee.png)

**Comment by Deep-Codes** [comment]
Awesome if you want create a PR Thanks for taking so much time 😇

**Comment by Deep-Codes** [comment]
Another solution:

https://mdxjs.com/guides/syntax-highlighting/

<img width="1440" alt="Screenshot 2022-01-26 at 10 20 32 AM" src="https://user-images.githubusercontent.com/61158210/151105797-c7043927-25f1-4e9c-8211-0334efd1a7fa.png">

**Comment by tusharnankani** [comment]
Ohh. That seems like a better fix xD
